name: Check Code

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".vscode"
      - "Dockerfile"
      - "LICENSE"
      - "mcp-template.json"
      - "README.md"
      - "template.env"
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.11", "3.12"]
        poetry-version: ["latest"]

    runs-on: ${{ matrix.os }}

    # TODO: Add type check once configured
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Poetry ${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: poetry run ruff check .
      - name: Format
        run: poetry run ruff format .
      - name: Test
        run: poetry run pytest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
